### ISSUE TITLE
Frame merging issue

### ISSUE THREAD

**Issue by ssheera** [Col-E/SimAnalyzer#4]
**Describe the bug**

> After it's visited a few methods it will start merging endlessly resulting in massive instruction lists and causing the program to hang

**Comment by ssheera** [comment]
Issue when seen from debugger
<img src="https://cdn.upload.systems/uploads/uI6SvWyg.png">
<img src="https://cdn.upload.systems/uploads/u2HwEtn9.png">

**Stacktrace**
<img src="https://cdn.upload.systems/uploads/Q5hqED2l.png">

**Comment by Col-E** [comment]
> After it's visited a few methods

Wait, just coming back to this now but are you re-using the analyzer across multiple methods? You're not supposed to do that. At least not with the current implementation logic of `SimAnalyzer.java`. Data isn't reset between usages.

**Comment by ssheera** [comment]
> > After it's visited a few methods
> 
> Wait, just coming back to this now but are you re-using the analyzer across multiple methods? You're not supposed to do that. At least not with the current implementation logic of `SimAnalyzer.java`. Data isn't reset between usages.

I create an Analyzer for each method

**Comment by ssheera** [comment]
```java
public static Map<AbstractInsnNode, Frame<AbstractValue>> computeSimFrames(ClassWrapper classNode, MethodNode method) {
        MethodAnalyzer analyzer = new MethodAnalyzer(new SimInterpreter());
        Map<AbstractInsnNode, Frame<AbstractValue>> frames = new HashMap<>();
        try {
            Frame<AbstractValue>[] _frames = analyzer.analyzeAndComputeMaxs(classNode.name, method);
            for (AbstractInsnNode instruction : method.instructions)
                frames.put(instruction, _frames[instruction.index]);
            return frames;
        } catch (Exception e) {
            e.printStackTrace();
            throw new RuntimeException("Failed to compute frames");
        }
    }
```
An example function to compute the sim frames for a method

**Comment by ssheera** [comment]
With the 1.8.1 release, it seems to be working fine
